const SafeCDPFactory = artifacts.require("SafeCDPFactory")
const SaiProxy = artifacts.require("SaiProxy")

module.exports = function (deployer, network) {
  let tub;

  // The addresses are from this page:
  // https://developer.makerdao.com/dai/1/api/
  if (network === "kovan") {
    tub = "0xa71937147b55deb8a530c7229c442fd3f31b7db2"
  } else if (network === "mainnet") {
    tub = "0x448a5065aebb8e423f0896e6c5d525c040f59af3"
  } else if (network === "test") {
    // This address is obtained from files generated by testchain:
    // https://github.com/makerdao/testchain
    tub = "0xe82ce3d6bf40f2f9414c8d01a35e3d9eb16a1761"
  } else {
    throw `unrecognized network ${network}`
  }

  deployer.deploy(SafeCDPFactory, tub, SaiProxy.address)
}